export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_LOAD_SUCCESS = "LOGIN_LOAD_SUCCESS";
export const LOGIN_LOAD_FAIL = "LOGIN_LOAD_FAIL";

export const LOGOUT = "LOGOUT";

export const REGISTER_LOADING = "REGISTER_LOADING";
export const REGISTER_LOAD_SUCCESS = "REGISTER_LOAD_SUCCESS";
export const REGISTER_LOAD_FAIL = "REGISTER_LOAD_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const LOADING_CREATED_PROGRAMS = "LOADING_CREATED_PROGRAMS";
export const LOAD_CREATED_PROGRAMS_SUCCESS = "LOAD_CREATED_PROGRAMS_SUCCESS";
export const LOAD_CREATED_PROGRAMS_FAIL = "LOAD_CREATED_PROGRAMS_FAIL";

export const CREATE_NEW_PROGRAM_LOADING = "CREATE_NEW_PROGRAM_LOADING";
export const CREATE_NEW_PROGRAM_SUCCESS = "CREATE_NEW_PROGRAM_SUCCESS";
export const CREATE_NEW_PROGRAM_FAIL = "CREATE_NEW_PROGRAM_FAIL";
export const CLEAR_CREATE_PROGRAM_SUCCESS = "CLEAR_CREATE_PROGRAM_SUCCESS";

export const UPDATE_PROGRAM_LOADING = "UPDATE_PROGRAM_LOADING";
export const UPDATE_PROGRAM_SUCCESS = "UPDATE_PROGRAM_SUCCESS";
export const UPDATE_PROGRAM_FAIL = "UPDATE_PROGRAM_FAIL";

export const DELETE_PROGRAM_LOADING = "DELETE_PROGRAM_LOADING";
export const DELETE_PROGRAM_SUCCESS = "DELETE_PROGRAM_SUCCESS";
export const DELETE_PROGRAM_FAIL = "DELETE_PROGRAM_FAIL";
export const CLEAR_DELETE_PROGRAM_SUCCESS = "CLEAR_DELETE_PROGRAM_SUCCESS";

export const INVITE_RESEARCHERS_LOADING = "INVITE_RESEARCHERS_LOADING";
export const INVITE_RESEARCHERS_SUCCESS = "INVITE_RESEARCHERS_SUCCESS";
export const INVITE_RESEARCHERS_FAIL = "INVITE_RESEARCHERS_FAIL";

export const GET_RESEARCHERS_LOADING = "GET_RESEARCHERS_LOADING";
export const GET_RESEARCHERS_SUCCESS = "GET_RESEARCHERS_SUCCESS";
export const GET_RESEARCHERS_FAIL = "GET_RESEARCHERS_FAIL";

export const GET_PUBLIC_PROGRAMS_LOADING = "GET_PUBLIC_PROGRAMS_LOADING";
export const GET_PUBLIC_PROGRAMS_SUCCESS = "GET_PUBLIC_PROGRAMS_SUCCESS";
export const GET_PUBLIC_PROGRAMS_FAIL = "GET_PUBLIC_PROGRAMS_FAIL";

export const GET_INVITED_PROGRAMS = "GET_INVITED_PROGRAMS";
export const GET_ENROLLED_PROGRAMS = "GET_ENROLLED_PROGRAMS";

export const POST_NEW_SUBMISSION = "POST_NEW_SUBMISSION";
export const GET_SUBMITTED_PROGRAMS = "GET_SUBMITTED_PROGRAMS";

export const GET_PROGRAMS_APPROVE_SUCCESS = "GET_PROGRAMS_APPROVE_SUCCESS";
export const GET_PROGRAMS_APPROVE_FAIL = "GET_PROGRAMS_APPROVE_FAIL";

export const GET_SUBMISSIONS_APPROVE_SUCCESS =
  "GET_SUBMISSIONS_APPROVE_SUCCESS";
export const GET_SUBMISSIONS_APPROVE_FAIL = "GET_SUBMISSIONS_APPROVE_FAIL";

export const GET_ALL_RESEARCHERS_SUCCESS = "GET_ALL_RESEARCHERS_SUCCESS";
export const GET_ALL_RESEARCHERS_FAIL = "GET_ALL_RESEARCHERS_FAIL";

export const GET_ALL_CUSTOMERS_SUCCESS = "GET_ALL_CUSTOMERS_SUCCESS";
export const GET_ALL_CUSTOMERS_FAIL = "GET_ALL_CUSTOMERS_FAIL";

export const SCAN_PROGRAM_LOADING = "SCAN_PROGRAM_LOADING";
export const SCAN_PROGRAM_SUCCESS = "SCAN_PROGRAM_SUCCESS";
export const SCAN_PROGRAM_FAIL = "SCAN_PROGRAM_FAIL";

export const GET_SCANNED_PROGRAMS_LOADING = "GET_SCANNED_PROGRAMS_LOADING";
export const GET_SCANNED_PROGRAMS_SUCCESS = "GET_SCANNED_PROGRAMS_SUCCESS";
export const GET_SCANNED_PROGRAMS_FAIL = "GET_SCANNED_PROGRAMS_FAIL";
